### ISSUE TITLE
Melhorar captura e tratamento de erros

### ISSUE THREAD

**Issue by rhandrade** [rhandrade/tray-theme#12]
### Descrição
Eu como usuário da ferramenta gostaria de uma comunicação clara quando erros ocorrem, no meu idioma principal. Como desenvolvedor gostaria padronizar os erros gerados e simplificar a captura deles.

### Motivo
Uma comunicação clara do problema facilita a tomada de decisões e permite continuar o desenvolvimento mais rápido. Além disso gera um código mais fácil de ler, escrever e manter.

### Detalhes
Acredito que podemos focar nos seguintes pontos:
- Criar um padrão de erros, utilizando a classe `Error` para obter tudo o que ela já traz.
- Fazer uma captura geral, de modo a simplificar a manutenção
- Validar possíveis falsos positivos / falsos negativos retornados pela API

**Comment by leolopes** [comment]
Reitero aqui então a pergunta que fiz em outro tópico: se você já sabe de alguns falsos positivos/negativos que ainda não estejam tratados, ou se será necessário ir descobrindo com o uso.

**Comment by rhandrade** [comment]
@leolopes Eu tinha mapeado mais um erro, relacionado aos arquivos `scss` não serem enviados, mesmo com o opencode dizendo que suporta o arquivo, mas conforme o uso podemos ir descobrindo mais. 

Alguns eu já corrigi na versão alpha-2, mas de forma mais pontual. Outro ponto importante é fazer o lançamento de erro, com alguma classe que estende Error, para assim ficar mais fácil manter o programa. Esse seria o objetivo principal. Elaborar essa captura geral de erros e como lança-los.

**Comment by leolopes** [comment]
Olá @rhandrade, eu não encontrei essa classe `Error` no código. Ela é algo padrão do Node?

**Comment by rhandrade** [comment]
@leolopes Essa classe `Error` é uma classe genérica do js. Da uma olhada [nesse link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error) da MDN para saber mais sobre.

**Comment by leolopes** [comment]
Ah, legal, eu nunca usei ela, mas vou dar uma olhada para tentar implementar essa tarefa.

**Comment by rhandrade** [comment]
Nova cli oficial já possui esse recurso.
