### ISSUE TITLE
Implementar "--watch" do Typescript

### ISSUE THREAD

**Issue by leolopes** [rhandrade/tray-theme#14]
# Descrição
Eu, como desenvolvedor, gostaria de ver as mudanças de script refletidas em tempo real, ao salvar os documentos originais em `.ts`, durante o desenvolvimento de mudanças no projeto.

# Motivo
Rodar o comando `npm run build` toda vez que um arquivo `.ts` é editado torna o trabalho muito tedioso e lento. Para grandes alterações, até que não seria o problema, mas se cada pequena mudança a ser testada requerer a ativação desse comando, o trabalho pode demorar demais e ser muito frustrante. Isso é algo especialmente comum quando estamos iniciando e fazendo os primeiros experimentos.

**Comment by leolopes** [comment]
Pessoal, registrei esta issue aqui para qualquer discussão, mas já estou implementando.

**Comment by rhandrade** [comment]
Show @leolopes... Achei bem legal essa sugestão e a implementação. Eu tava usando o próprio vscode para ficar compilando automaticamente quando tinha modificação, mas a sua sugestão é melhor pois fica visível a todos do projeto. 

Deixei um comentário também lá na sua PR. Veja la depois.

**Comment by rhandrade** [comment]
Fechado pois a PR que implementa esse recurso foi dado merge.
