### ISSUE TITLE
Comando "new" com "theme_base" não surtiu efeito

### ISSUE THREAD

**Issue by leolopes** [rhandrade/tray-theme#19]
## Descrição

Ao rodar o comando `tray new` incluindo o parâmetro `theme_base` não surtiu o efeito esperado. O novo tema, em vez de ser baseado no tema base, foi gerado a partir do tema padrão da Tray.

**Comment by rhandrade** [comment]
@leolopes Consegue verificar se esse comportamento se repete ao usar o `opencode new` da Tray? Nele a Tray passa o nome do tema a ser usado como base e caso não passe nenhum ele usa o `default`. 

Repare que se o tema foi criado pela interface web, os nomes no `opencode list` são diferentes (até hoje não entendi o porque), e isso pode afetar o comando new com o parâmetro `theme_base`. 

Se conseguir fazer esses testes e postar o resultado aqui agradeceria.

**Comment by leolopes** [comment]
@rhandrade o parâmetro `theme_base` é o nome do tema então? Eu achei que seria o código.

**Comment by Merieli** [comment]
@rhandrade e @leolopes eu testei de várias formas então acho que posso contribuir. O próprio comando **opencode new** da Tray não está funcionando e também gera o tema a partir do padrão tray. 
A tentativa foi realizada com o tema base **Car Parts**

Como testei:
- nome do tema base [usei o nome existente do opencode list]
- código do tema base
- nome do tema base entre aspas [devido ao espaço existente no nome pensei que poderia ser o problema]
- nome do tema base substituindo o espaço por um "**_**"

Da mesma forma testei utilizando o comando **tray new** e ocorre o mesmo.

**Comment by leolopes** [comment]
Obrigado @Merieli!
Imagino então que o problema seja com a API, que não está respeitando o comando.
Quem sabe tenhamos que deixar o comando no código mas logar algum aviso indicando que talvez não funcione.

**Comment by rhandrade** [comment]
Obrigado pelos testes @Merieli, ajudou muito a gente validar aqui 🙂 

@leolopes Já abri um chamado na Tray sobre essa questão e eles verificaram que o problema é do lado deles mesmo. O comando está ignorando o parâmetro theme_base. Eles falaram que o pessoal iria verificar o porque isso acontece. Até lá vamos colocar um log informando que o parâmetro theme_base pode não ser refletido devido a problemas na API.

Já adicionei essa issue para a versão 1.0.0. Vlw pessoal!!! 👏

**Comment by rhandrade** [comment]
Já fiz um PR que adiciona um log informando o problema com esse parâmetro. Vlw toda a ajuda pessoal, vocês são demais! 👍
