### ISSUE TITLE
Upload de arquivos e pastas base

### ISSUE THREAD

**Issue by rhandrade** [rhandrade/tray-theme#21]
### Descrição
Eu como usuário do CLI gostaria de poder enviar somente as pastas principais 'core' do tema. As demais pastas específicas, como imagens, seriam feitas por um comando a parte.

 _Sugestão indicada pelo @thiagofloriano_

### Motivo
Muitas vezes queremos enviar somente uma base do tema para não poluir o tema com coisas que não farão sentido, como imagens ou scripts adicionais. Para isso um comando de upload _core_ seria interessante. Como sugerido pelo @thiagofloriano seria enviado apenas a base essencial da Tray `settings / css / js / pages / layout`. Imagens e outras particularidades seriam enviadas a parte.

### Dependência
Esse funcionalidade depende da implementação de:
- #17

**Comment by rhandrade** [comment]
Issue fechado, pois feature foi implementada.
Versão 1.1.0 liberada! Vlw pessoal 🎉

**Comment by thiagofloriano** [comment]
Muito bom!! 👏
