### ISSUE TITLE
Detalhamento das opções no readme

### ISSUE THREAD

**Issue by thiagofloriano** [rhandrade/tray-theme#25]
## Descrição
Eu como desenvolvedor gostaria que na documentação do projeto constassem as opções de cada comando e os novos comandos disponíveis.

## Motivo
Atualizar a documentação com as novas opções e comandos disponibilizados pelas novas versões tornará mais fácil o uso e, possivelmente, a adesão de novos usuários ao projeto.

**Comment by rhandrade** [comment]
Resolvido pelo commit #27
