### ISSUE TITLE
Erro ao gerar o config.yml

### ISSUE THREAD

**Issue by fagnanigm** [rhandrade/tray-theme#28]
E ai galera, beleza?

Estou tentando alterar um tema aqui e ao tentar rodar o comando tray configure [key] [pass] [theme_id] estou recebendo a mensagem de que alguma dessas informações estão erradas. 

Não estou certo sobre o THEME_ID, é o numero que está na URL ao editar um tema na plataforma da tray (https://opencode.tray.com.br/v2/themes/THEME_ID/customizations)? 

Fico no aguardo.

Obrigado!

**Comment by rhandrade** [comment]
E ai @fagnanigm tudo certo e contigo? Então, não... o theme_id é o código do tema que aparece na listagem de temas no painel da Tray. O código que aparece na URL como vc mencionou é outro código de uso interno da Tray. 

A imagem abaixo mostra o código que você precisa usar junto com o tray-theme:
![image](https://user-images.githubusercontent.com/4511733/141663881-15f4f04a-f1a5-47e6-b7b4-8bd259b929d3.png)

Espero ter ajudado 🙂
