### ISSUE TITLE
Não funcionou na instalação local

### ISSUE THREAD

**Issue by thiagofloriano** [rhandrade/tray-theme#3]
```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'fs/promises'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)

**Comment by rhandrade** [comment]
@thiagofloriano Você esta usando qual versão do Node.js? Por enquanto na versão `alpha` testei somente na versão mais recente do Node.js que já vem com as promises para o FS.

**Comment by thiagofloriano** [comment]
> @thiagofloriano Você esta usando qual versão do Node.js? Por enquanto na versão `alpha` testei somente na versão mais recente do Node.js que já vem com as promises para o FS.

Realmente, Rafael, na versão mais recente do Node.js funcionou. Eu estava rodando 10.x. Obrigado pela atenção.
