### ISSUE TITLE
Delete not working

### ISSUE THREAD

**Issue by juanfariasdev** [rhandrade/tray-theme#5]
Delete-theme not working. 
Response from Api is: Error from api: Layout inválido

**Comment by rhandrade** [comment]
@juanfariasdev O endpoint de remoção dos temas na API da Tray só consegue remover temas que estão criados e listados no painel administrativo da Tray.

Ao rodar o comando `tray delete-theme <id>` , o CLI vai mandar a requisição para o servidor e pode acontecer dois casos:

1. Se o tema ainda existe nos servidores da Tray, ou seja, se entrar no painel admin da Tray ele está disponível na listagem, o tema é removido, mas a Tray retorna um erro interno do servidor, algo como `undefined method 'id'`. A versão mais recente do do meu CLI já trata isso e exibe uma mensagem apropriada, mostrando que o tema foi removido.
2. Se o tema não existe mais nos servidores da Tray, ou seja, se entrar no painel admin da Tray ele **não** está disponível na listagem, então o tema retorna o erro que você citou,  `Layout inválido`.

Acredito que a confusão venha do comando `tray themes`. Ao rodar esse comando, os temas listados pelo CLI são exatamente os mesmos que o comando `opencode list` também exibe, somente uma formatação diferente. Esse é o retorno que a API do opencode me retorna 😕. Infelizmente a Tray não retorna somente os temas disponíveis.

Infelizmente esse tipo de comportamento eu não consigo contornar, pois não tenho acesso aos servidores na Tray para corrigir esses problemas.

Sempre que você obter um erro no qual a mensagem contenha `Error from api:` significa que eu já tratei os retornos e que para esse retorno não possuo alternativa a não ser exibir para o usuário, ou seja, não é erro do CLI propriamente dito.
