### ISSUE TITLE
Suporte a múltiplos sistemas operacionais

### ISSUE THREAD

**Issue by rhandrade** [rhandrade/tray-theme#8]
### Descrição 
Eu como usuário do CLI gostaria de poder usar a ferramenta no meu sistema operacional preferido, estou acostumado, ou ao qual serve para meu workflow.

### Motivo
Existes vários sistemas operacionais, cada qual voltado a um mercado ou finalidade específica. Ao fazer a ferramenta ser compatível com vários sistemas operacionais permite que mais pessoas possam usufruir dos benefícios que ela traz, além de não forçar uma mudança no ambiente que funciona para determinado indivíduo ou trabalho.

### Detalhes
Acredito que os principais sistemas que deveriam ser suportados são:
- Windows 10
- macOS 11
- macOS 10.15
- Ubuntu 20.04
- Ubuntu 18.04

**Comment by leolopes** [comment]
Só comentando aqui que os testes que estou fazendo são no Windows 10. Posso fazer ainda no Ubuntu. Em demais, só com máquina virtual.

**Comment by thiagofloriano** [comment]
Posso testar com Ubuntu 20 e MacOS 11, se precisarem.

**Comment by leolopes** [comment]
Oi @thiagofloriano , se conseguir baixar o branch do meu último PR e mesclar com o outro PR, vais ter um "master" improvisado. Aí daria para testar nesses dois OS e ver se aparece algum erro diferente dos do Windows.
Pro Windows 10, parece estar rodando bem.

@rhandrade , será que temos que estabelecer algum critério de sucesso para esta tarefa?

**Comment by leolopes** [comment]
A saber: no Ubuntu 18, que é o que eu tenho, rodaram todos os comandos.

**Comment by rhandrade** [comment]
@thiagofloriano Agradeceria muito se pudesse testar nesses sistemas. Acredito que se rodar tudo certo no macOS 11, rodará também no macOs 10.15.

@leolopes Para validar as versões do Node.js que funcionavam eu verifiquei se todos os comandos estavam funcionando corretamente. Acredito que mais para frente no projeto podemos colocar testes automatizados para fazer essas validações nos códigos que forem sendo gerados. Podemos trazer essa discussão novamente depois de finalizamos as questões atuais, o que acha?

**Comment by rhandrade** [comment]
De acordo com a página de [ciclo de lançamentos da Canonical](https://ubuntu.com/about/release-cycle), acho que seria legal darmos suporte apenas as LTS até o nível `Maintenance updates` ou as duas últimas versões LTS.

Vejam a imagem abaixo, extraída da página acima no dia 11/09/2021:
![image](https://user-images.githubusercontent.com/4511733/132951973-397a872e-6751-4ec4-a058-96c7be17d4cb.png)

**Comment by leolopes** [comment]
> 
> Acredito que mais para frente no projeto podemos colocar testes automatizados para fazer essas validações nos códigos que forem sendo gerados. Podemos trazer essa discussão novamente depois de finalizamos as questões atuais, o que acha?

Boa ideia. Eu ainda não criei testes automatizados; tens algum pacote que sugeres para isso?

**Comment by thiagofloriano** [comment]
Acabei de testar no MacOS 11 e deu certo por aqui. Só não consegui testar alguns comandos como `clean-cache` ou ter certeza que o `delete-theme` funcionou porque não tenho acesso ao painel administrativo, mas de resto rodou tudo bem. Só fiquei intrigado com as mensagens dizendo que a API retornou falso negativo. Também acho que algumas mensagens podem ser mais descritivas, mas isso é mero detalhe.

**Comment by leolopes** [comment]
Olha, o `clean-cache` acho que nem temos como testar, pois não temos acesso nem via painel nem pela linha de comando à qualquer informação de cache, a não ser que a API retorne alguma informação a respeito e eu não saiba.

O `delete-theme` não surtiu efeito. O tema ainda está no painel. Mas se o comando rodou, enviou a requisição à API, recebeu resposta positiva, etc, aí talvez o problema seja na API da Tray mesmo.

**Comment by thiagofloriano** [comment]
> Olha, o `clean-cache` acho que nem temos como testar, pois não temos acesso nem via painel nem pela linha de comando à qualquer informação de cache, a não ser que a API retorne alguma informação a respeito e eu não saiba.
> 
> O `delete-theme` não surtiu efeito. O tema ainda está no painel. Mas se o comando rodou, enviou a requisição à API, recebeu resposta positiva, etc, aí talvez o problema seja na API da Tray mesmo.

@leolopes dá uma olhadinha se tem 2 temas novos lá... testei o `delete-theme` com os que criei com o `new`.

**Comment by leolopes** [comment]
@thiagofloriano, ah, não tem mesmo. Achei que ias excluir aquele ID que te passei. 
Se não tem novos, imagino então que os tenha excluído com sucesso hehehe.

Nesse caso, eu diria que está tudo funcionando. Quem sabe já dê para concluir essa issue, @rhandrade?

**Comment by rhandrade** [comment]
> Boa ideia. Eu ainda não criei testes automatizados; tens algum pacote que sugeres para isso?

@leolopes Eu vejo o pessoal comentando bastante do [Jest](https://jestjs.io) e ele é usado por grandes empresas para criar testes, como Facebook, Twitter e Spotify. Acho que seria legal no futuro utilizarmos ele para ajudar nos testes das novas features.

> Só fiquei intrigado com as mensagens dizendo que a API retornou falso negativo. Também acho que algumas mensagens podem ser mais descritivas, mas isso é mero detalhe.

Sim @thiagofloriano acredito que podemos melhorar essas mensagens. O @leolopes já tinha levantado isso antes, mas esse foi um jeito de indicar que a ação foi feita corretamente mas que teve um retorno negativo, de maneira que quem estiver utilizando entenda que deu certo.

> Nesse caso, eu diria que está tudo funcionando. Quem sabe já dê para concluir essa issue, @rhandrade?

Claro! Vamos dar como concluída. Vlw pessoal por toda a ajuda, sem vocês isso não seria possível! E desculpem a demora pra resolver, essa semana foi muito corrida. E vamos pra cima 🚀
